function getInfo() {
	window.numberOfQuestions = 	10;
	window.currentSlide = 		0;
	window.currentScore = 		0;
	window.title = 				"Minnesota Wild Trivia";
	window.questions = [		"WHAT WAS THE FIRST NHL FRANCHISE IN MINNESOTA?", 
								"WHAT YEAR DID THE WILD ENTER THE NHL?",
								"WHO DID THE WILD DRAFT IN THE FIRST ROUND OF THEIR INAUGURAL SEASON?", 
								"WHAT TEAM ENTERED THE LEAGUE IN 2000 WITH THE WILD?",
								"WHAT SEASON DID THE WILD FIRST MAKE IT TO THE PLAYOFFS?", 
								"WHAT IS THE NAME OF THE VENUE THAT THE WILD PLAY AT?", 
								"WHO IS THE WILD'S ALL TIME LEADING GOAL SCORER?", 
								"WHO IS THE WILD'S ALL TIME LEADING POINT GETTER?", 
								"WHO HOLDS THE RECORD FOR MOST GOALS SCORED IN A GAME BY A WILD PLAYER?", 
								"WHICH WILD PLAYER HAS BEEN TEAM CAPTAIN FOR THE LONGEST?" ];

	window.correctAnswer = [ 	"D", "C", "A", "B", "E", "D", "C", "A", "B", "E" ]; 

	window.answerA = [ 			"SAINT PAUL SAINTS", 
								"1999",
								"MARIAN GABORIK",
								"WINNIPEG JETS",
								"2012-2013",
								"MARIUCCI ARENA",
								"ZACH PARISE", 
								"MIKKO KOIVU", 
								"NINO NIEDERREITER", 
								"ZACH PARISE" ];
	window.answerB = [ 			"MINNEAPOLIS LAKERS", 
								"2002",
								"NICK SCHULTZ",
								"COLUMBUS BLUE JACKETS",
								"2006-2007",
								"MET CENTER",
								"JASON ZUCKER", 
								"RYAN SUTER", 
								"MARIAN GABORIK", 
								"ERIC STAAL" ];			
	window.answerC = [ 			"MINNESOATA SWARM", 
								"2000",
								"MIKKO KOIVU",
								"NASHVILLE PREDATORS",
								"2008-2009",
								"HHH METRODOME",
								"MARIAN GABORIK", 
								"ZACH PARISE", 
								"JASON ZUCKER", 
								"RYAN SUTER" ]; 			
	window.answerD = [ 			"MINNESOTA NORTH STARS", 
								"2004",
								"BRENT BURNS",
								"FLORIDA PANTHERS",
								"2000-2001",
								"XCEL ENERGY CENTER",
								"MIKKO KOIVU", 
								"MARIAN GABORIK", 
								"ZACH PARISE", 
								"JASON POMINVILLE" ]; 			
	window.answerE = [ 			"MINNESOTA MIGHTY DUCKS", 
								"1998",
								"PIERRE-MARC BOUCHARD",
								"ATLANTA THRASHERS",
								"2002-2003",
								"TARGET CENTER",
								"ANDREW BRUNETTE", 
								"PIERRE-MARC BOUCHARD", 
								"BRIAN ROLSTON", 
								"MIKKO KOIVU" ]; 			



	window.response = [ 		"THE MINNESOTA NORTH STARS JOINED THE NHL IN 1967. PLAYING THERE UNTIL THEY WERE SOLD TO DALLAS IN 1993.", 
								"ALTHOUGH THE WILD WERE FOUNDED IN 1997, THEY DID NOT PLAY THEIR FIRST GAME UNTIL THE 2000-2001 SEASON.", 
								"THE WILD SELECTED MARIAN GABORIK THIRD OVERALL IN THE 2000 NHL DRAFT.", 
								"THE COLUMBUS BLUE JACKETS ALSO ENTERED THE NHL IN THE 2000-2001 NHL SEASON.", 
								"THE WILD'S FIRST PLAOFF APPEARANCE CAME IN 2002-2003 SEASON WHERE THEY MADE IT ALL THEY WAY TO THE CONFERNCE FINALS.",
								"THE WILD PLAY AT THE XCEL ENERGY CENTER IN SAINT PAUL.",
								"THE WILD'S LEADING GOAL SCORER IS MARIAN GABORIK WITH 219 GOALS.",
								"THE WILD'S LEADING POINT GETTER IS MIKKO KOIVU WITH 709 POINTS.",
								"MARIAN GABORIK SCORED 5 GOALS ON DEC. 20, 2007 AGAINST THE NEW YORK RANGERS.",
								"MIKKO KOIVU WAS NAMED PERMANENT CAPTAIN ON OCT. 20, 2009 AND HAS WORN THE C EVER SINCE." ];
							
}
						